### PR TITLE
Update quickstart create package file

### PR DESCRIPTION
**Pull request by deniscapeto**
updated file create-and-publish-a-package-using-visual-studio.md. 
The sentence "Defina a configuração como **Versão**" makes no sense in portuguese.

### CODE REVIEW

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by v-elcou** [comment]
Hello @deniscapeto, 
Thank for your contribution. We are currently reviewing and will communicate the decision taken. 
Thanks for your time and support on this.

Kind regards,
Microsoft C&E Localization Team

**Comment by LisandroSu** [comment]
@deniscapeto :

Thank you for your feedback and suggestion!

We agree with your suggestions, and we will include them into the next article update release.

Thank you for your time and support.
Microsoft C&E Localization Team

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Pull request merged**
